// Variables of the user-manual folder contents. Generated by user-manual-preprocess.js
userManualSections = {
    "0 - Introduction": {
        "level": 0
    },
    "1 - Login": {
        "level": 0
    },
    "1.1 - Login Screen": {
        "level": 1,
        "html": "<h2>1.1 - Login Screen</h2>\r\n\r\n<p>\r\n\tThe login screen is the first screen to be encountered when opening the program. Here, the user can be verified before using the system.\r\n</p>\r\n\r\n<center><img src=\"images/login-screen.png\"></img></center>\r\n\r\n<center><i>The login screen</i></center>\r\n\r\n<!-- Ordered List (1., 2., ...)-->\r\n<ol>\r\n\t<li>\r\n\t\t<b>Username Field</b> - The user will enter their username here.\r\n\t</li>\r\n\t<li>\r\n\t\t<b>Password Field</b> - The user will enter their password here.\r\n\t</li>\r\n\t<li>\r\n\t\t<b>Login Button</b> - After filling out the username and password fields, the user can click the login button to verify these credentials. If the verification is successful, they will be logged in in the system.\r\n\t</li>\r\n\t<li>\r\n\t\t<b>Forgot Password Link</b> - The user can click this link to proceed to the forgot password procedure.\r\n\t</li>\r\n</ol>"
    },
    "2 - Interface": {
        "level": 0
    },
    "3 - Customer Management": {
        "level": 0
    },
    "4 - Point of Sales": {
        "level": 0
    },
    "5 - Inventory Management": {
        "level": 0
    },
    "6 - User Management": {
        "level": 0
    },
    "7 - Report": {
        "level": 0
    },
    "8 - Backup and Restore": {
        "level": 0
    },
    "9 - Help": {
        "level": 0
    },
    "10 - About": {
        "level": 0
    }
}